name = "neyy-luau-decompiler"
main = "build/worker/shim.mjs"
workers_dev = true
compatibility_date = "2026-09-19"

[build]
command = "cargo install -q worker-build --version 0.8.6 --locked && worker-build --release"
